"""add conversations and messages tables

Revision ID: 56812e3f6459
Revises: 2b5cbc0c8125
Create Date: 2026-08-05 15:00:42.235338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56812e3f6459'
down_revision: Union[str, Sequence[str], None] = '2b5cbc0c8125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
